### ISSUE TITLE
About the ore registry name and the item tag namespace

### ISSUE THREAD

**Issue by skyraah** [yanny7/ytech#1]
- I've noticed a couple issues. Regarding the tag name, it should be "forge:sth." instead of "ytech:sth.", which will fit more mods and reduce the workload of modpackers!
- And there is another problem, ytech uses "cassiterite" instead of "tin" for the registry name related to tin materials, which is not a common name used by most mod communities and modpacks. Perhaps a tag for "tin" could be added to it.
- One last thing about mod play, due to the lack of in-game guidelines and wiki, I don't really know how some of the blocks work (e.g. millstone and aqueduct).

**Comment by yanny7** [comment]
Thank you for reporting issues.

- I used ytech prefix for mod specific items, if there is (neo)forge version of tag, I use this
- Cassiterite is because I want to be this specific mineral. But I can add also tin tag
- There are item descriptions on e.g. aqueduct related items, but if you are missing another important info please be more specific

**Comment by skyraah** [comment]
- sry i  only checked the tag for the plate items. like golden plate's tag , only "#ytech:plates" or "#ytech:plates/gold" here, if you add another tag like "#forge:plates", that's even better ;-)
- Off topic, the discord link is not working again

**Comment by yanny7** [comment]
- is there some community repository with general forge tags? because I use offical tags from https://github.com/MinecraftForge/MinecraftForge/tree/1.20.x/src/main/generated/data/forge/tags/items, but there isn't forge:plages tag
- thank you, I fixed it
